In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
pd.options.mode.chained_assignment = None   # its used for some errors are ignoring

In [ ]:
fraud = pd.read_csv('/content/Fraud_check.csv')
fraud.head()

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO

In [ ]:
fraud1 = fraud.rename({'Marital.Status':'Married','Taxable.Income':'Tax','City.Population':'Population','Work.Experience':'Work'},axis=1)

In [ ]:
fraud1.dtypes

Undergrad     object
Married       object
Tax            int64
Population     int64
Work           int64
Urban         object
dtype: object

In [ ]:
fraud1['tax'] = fraud1.Tax.map(lambda x:1 if x<=30000 else 0)

In [ ]:
fraud1.head()

  Undergrad   Married    Tax  Population  Work Urban  tax
0        NO    Single  68833       50047    10   YES    0
1       YES  Divorced  33700      134075    18   YES    0
2        NO   Married  36925      160205    30   YES    0
3       YES    Single  50190      193264    15   YES    0
4        NO   Married  81002       27533    28    NO    0

In [ ]:
#converting data types
fraud1['Married'] = fraud1['Married'].astype('category')
fraud1['Undergrad'] = fraud1['Undergrad'].astype('category')
fraud1['Urban'] = fraud1['Urban'].astype('category')

In [ ]:
# convert datatype category to numeric
fraud1['Married'] = fraud1['Married'].cat.codes
fraud1['Undergrad'] = fraud1['Undergrad'].cat.codes
fraud1['Urban'] = fraud1['Urban'].cat.codes

In [ ]:
fraud1.dtypes

Undergrad      int8
Married        int8
Tax           int64
Population    int64
Work          int64
Urban          int8
tax           int64
dtype: object

In [ ]:
fraud1.drop('Tax',axis=1)

     Undergrad  Married  Population  Work  Urban  tax
0            0        2       50047    10      1    0
1            1        0      134075    18      1    0
2            0        1      160205    30      1    0
3            1        2      193264    15      1    0
4            0        1       27533    28      0    0
..         ...      ...         ...   ...    ...  ...
595          1        0       39492     7      1    0
596          1        0       55369     2      1    0
597          0        0      154058     0      1    0
598          1        1      180083    17      0    0
599          0        0      158137    16      0    0

[600 rows x 6 columns]

In [ ]:
data2 = fraud1.values

In [ ]:
X = data2[:,0:5]
Y = data2[:,5:]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

In [ ]:
#Random forest
kfold = KFold(n_splits = 10 , random_state =10, shuffle=True)

In [ ]:
model3 = RandomForestClassifier(n_estimators=100,max_depth=5,min_samples_split=20)
model3.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, min_samples_split=20)

In [ ]:
results = cross_val_score(model3 , x_train, y_train, cv = kfold)

In [ ]:
print('Train accuracy: {}'.format(model3.score(x_train, y_train)))

Train accuracy: 0.7395833333333334